### ISSUE TITLE
[Feature request] Group commands

### ISSUE THREAD

**Issue by BachiMjavanadze** [SeeLog/commando#28]
Please add ability to group commands. Add one more variable into settings, say `group`:

`"group": "Angular"`

after calling your extension you should see:

![image](https://user-images.githubusercontent.com/38082501/182691972-78150d47-5681-45ef-8f94-8eaf1b6fe065.png)

and after clicking on Angular you should see only commands that are grouped ander `Angular`:

![image](https://user-images.githubusercontent.com/38082501/182692193-6e19d7d9-5371-405a-8b28-f9870793e84f.png)

**Comment by SeeLog** [comment]
Do you want hierachical command interface?
Or do you just want to see commands that are related to your project?

If the latter, you can add `.vscode/settings.json` to your project.
If the former, this is not easy problem, because data structure will be more complex.

Commando is focused on executing commands(e.g.  unittest commands that are often used) quickly, so I reluctant to implement hierachical commands.

**Comment by BachiMjavanadze** [comment]
> Do you want hierachical command interface? Or do you just want to see commands that are related to your project?

I'll explain my case: I'm full-stack developer and I need to separate front-end commands end back-end commands. So I do not need project-related commands. Grouping commands are olready implemented in old extensions (they are not supported now).  i.e.: [Run Terminal Command](https://marketplace.visualstudio.com/items?itemName=adrianwilczynski.terminal-commands)

**Comment by SeeLog** [comment]
Ah, OK.
I understand what you want maybe.

Command pallet
↓
Commando: Execute command
↓
Show the list of commands, and also group
↓
If select group, filter commands with group, and then show list

So, this is not hierachical, just filter.
Is this correct?

**Comment by BachiMjavanadze** [comment]
> Ah, OK. I understand what you want maybe.
> 
> Command pallet ↓ Commando: Execute command ↓ Show the list of commands, and also group ↓ If select group, filter commands with group, and then show list
> 
> So, this is not hierachical, just filter. Is this correct?

yes. but it does not matter if you are not goin to implement ather features.

Good luck to you!

**Comment by SeeLog** [comment]
I implemented this feature in #31.
Please wait for the next release.
