### ISSUE TITLE
[Feature request] Add icon on Status Bar

### ISSUE THREAD

**Issue by BachiMjavanadze** [SeeLog/commando#29]
Please add extension icon on `Status Bar` to call commands:

![image](https://github.com/SeeLog/commando/assets/38082501/25970828-755e-4e6f-ba40-092c0ae8d2cc)

**Comment by SeeLog** [comment]
This is good I think, however it should not force to show on Status bar.
Status bar's area is limited, so lots of information will lose UXs.
So, if I will implement this feature in the future, it will be optional to show in status bar if I can.

**Comment by BachiMjavanadze** [comment]
> it will be optional to show in status bar

Of course it should be optional and to save Status Bar space you may put there actual icon

![image](https://github.com/SeeLog/commando/assets/38082501/f1a7c000-534b-402c-80cf-29d8a0fc959b)

**Comment by SeeLog** [comment]
I implemented this feature #30.
Please wait for next release.
